### ISSUE TITLE
Can't get parental and custon raiting of an item

### ISSUE THREAD

**Issue by ftoek** [radityaharya/jellyfinapi#1]
I'm trying to manipulate fields parental rating and custom rating of an item, however, I don't have CustomRating value in the BaseItemDto object returned in the callback.
This is the a part of code I'm using:
```
item_res = items_controller.get_items_by_user_id(user_id=admin_id, parent_id=PARENT_ID)
re_query = re.compile("Boss")
for item in item_res.items:
    if re_query.search(item.name):
        print(f"{item.id} -> {item.name}, {item.official_rating},  {item._names['official_rating']}, {item._names['custom_rating']}")
```
and this is what I get
```
8b50ea0970c187473115191fa298ac9d -> The.Boss.Baby, RU-12+,  OfficialRating, CustomRating
```

![image](https://github.com/radityaharya/jellyfinapi/assets/3242837/ce569f37-e57b-4f24-9a96-b3b659402c39)

Any ideas? maybe I'm doing something wrong?

**Comment by radityaharya** [comment]
I tried replicating the issue on my instance and it yielded the same result. For some reason the response from the "/Users/{userId}/Items" endpoint doesn't return the CustomRating value. I haven't updated this library since [jellyfin-openapi-10.8.5](https://api.jellyfin.org/openapi/stable/jellyfin-openapi-10.8.5.json) dated 25-Sep-2022, things might've changed that I'm not aware of. I'll have a look at it over the weekend.

**Comment by ftoek** [comment]
I figured this out this is not an issue, this is a feature, `JellyfinapiClient.get_items` by default fetches just a few fields, if you need more fields you have to specify them explicitly, this is a working code
```
from jellyfinapi.jellyfinapi_client import JellyfinapiClient
client = JellyfinapiClient(
    x_emby_token='xxx',
    server_url="http://host-name:8096/")
items_controller = client.items
item_res = items_controller.get_items(ids="8b50ea0970c187473115191fa298ac9d", fields="CustomRating,People")
``` 
`fields="CustomRating,People"` here I defined data fields I need to process
